name = "LaTeXEscapes"
uuid = "cf6549fa-34fa-4b85-907d-0f184605242c"
authors = ["Tamás K. Papp <tkpapp@gmail.com>"]
version = "0.1.0"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"

[compat]
Automa = "1"
DocStringExtensions = "0.9"
LaTeXStrings = "1.3.1"
julia = "1.10"
